name: instagram
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cloud_firestore: ^3.3.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.4.2
  firebase_core: ^1.19.2
  firebase_storage: ^10.3.2
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^1.1.1+1
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  provider: ^6.0.3
  readmore: ^2.2.0
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true

  assets:
    - assets/
